export default {
  grid: {
    container: "130rem",
    gutter: "3.2rem",
  },
  border: {
    radius: "0.4rem",
  },
  font: {
    family: "Poppins, sans-serif",
    text: "Inter, sans-serif",
    light: 300,
    normal: 400,
    bold: 600,
    sizes: {
      xsmall: "1.2rem",
      small: "1.4rem",
      medium: "1.6rem",
      large: "1.8rem",
      xlarge: "2.0rem",
      xxlarge: "2.2rem",
      huge: "2.4rem",
    },
  },
  colors: {
    primary: "#32B768",
    cleanPrimary: "#DAF2E4",
    darkPrimary: "#2B7A4B",
    darkDarkPrimary: "#19472C",
    secondary: "#3D7199",
    mainBg: "#FCFBFC",
    secondaryBg: "#EDEFF4",
    white: "#fff",
    black: "#000",
    lightGray: "#EAEAEA",
    contour: "#DBDDE6",
    shape: "#F0F0F0",
    gray: "#878787",
    cleanGray: "#A9ABAE",
    systemRed: "#E44040",
    yellow: "#FFC779",
  },
  spacings: {
    xxsmall: "0.8rem",
    xsmall: "1.6rem",
    small: "2.4rem",
    medium: "3.2rem",
    large: "4.0rem",
    xlarge: "4.8rem",
    xxlarge: "5.6rem",
  },
  layers: {
    base: 10,
    menu: 20,
    overlay: 30,
    modal: 40,
    alwaysOnTop: 50,
  },
  transition: {
    default: "0.3s ease-in-out",
    fast: "0.1s ease-in-out",
  },
  shadows: {
    main: "0px 0px 8px rgba(0, 0, 0, 0.1);",
    secondary: "0px 2px 8px rgba(0, 0, 0, 0.2);",
    sidebar: "4px 4px 5px #F0F0F0",
  },
} as const;
